export const EMOJIS: { [key: string]: string } = {
  bug: '🐛',
  perf: '🚀',
  time: '⏳',
  fast: '⚡',
  fire: '🔥',
  trash: '🗑️',
  warning: '⚠️',
  error: '❌',
  solution: '✔️',
  todo: '📋',
  build: '🚧',
  add: '➕',
  remove: '➖',
  remind: '🔔',
  feat: '✨',
  idea: '💡',
  breaking: '💥',
  refactor: '🔨',
  test: '✅',
  styles: '🎨',
};
