"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var hono_1 = require("hono");
var cors_1 = require("hono/cors");
var users_1 = require("./routes/users");
var lists_1 = require("./routes/lists");
var app = new hono_1.Hono().basePath("/api");
app.use((0, cors_1.cors)());
app.route("/users", users_1.appUser);
app.route("/lists", lists_1.appList);
exports.default = app;
